In [121]:
from huggingface_hub import HfApi

import os
from google.colab import userdata

In [ ]:
api = HfApi(token='yout token')

In [123]:
# api.create_repo(
#     repo_id="mohd-musheer/fristrepo",  # full path
#     repo_type="model",                         # or just skip (default is model)
#     private=False                              # set True for private repo
# )

In [124]:
# api.upload_file(
#     path_or_fileobj="/content/Musheer ML CV.docx",
#     path_in_repo="Musheer ML CV.docx",  # Where it goes in repo
#     repo_id="mohd-musheer/fristrepo"  # Same as created above
# )

In [125]:
from datasets import load_dataset
dataset=load_dataset('stanfordnlp/imdb')
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [126]:
print(dataset.shape)

{'train': (25000, 2), 'test': (25000, 2), 'unsupervised': (50000, 2)}

In [127]:
import pandas as pd

train_df = pd.DataFrame(dataset['train'])
test_df = pd.DataFrame(dataset['test'])

df = pd.concat([train_df, test_df])

df.info

<bound method DataFrame.info of                                                     text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  Just got around to seeing Monster Man yesterda...      1
24996  I got this as part of a competition prize. I w...      1
24997  I got Monster Man in a box set of three films ...      1
24998  Five minutes in, i started to feel how naff th...      1
24999  I caught this movie on the Sci-Fi channel rece...      1

[50000 rows x 2 columns]>

In [141]:
df.head()

                                                    text  label
3312   El Padrino :The Latin Godfather - while this s...      0
2428   I was true to my regard for Mr. Glover and Ms....      0
20384  This super creepy Southern Gothic melodrama st...      1
7144   The guy did a lot of title design for a bunch ...      0
8573   What is happening to ITV Drama. First, "Losing...      0

In [128]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [129]:
df=df.sample(100)
df.shape

(100, 2)

In [130]:
api.create_repo(
    repo_id='mohd-musheer/imdb100',
    repo_type='dataset',
    private=False
)

RepoUrl('https://huggingface.co/datasets/mohd-musheer/imdb100', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mohd-musheer/imdb100')

In [131]:
from datasets import Dataset
dataset = Dataset.from_pandas(df)
dataset.push_to_hub("mohd-musheer/imdb100")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 93.7kB / 93.7kB

CommitInfo(commit_url='https://huggingface.co/datasets/mohd-musheer/imdb100/commit/1763d369d7f10571c5873781ce18a84d3dc51b50', commit_message='Upload dataset', commit_description='', oid='1763d369d7f10571c5873781ce18a84d3dc51b50', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/mohd-musheer/imdb100', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mohd-musheer/imdb100'), pr_revision=None, pr_num=None)

In [137]:
from transformers import AutoTokenizer , AutoModel
tokenizer=AutoTokenizer.from_pretrained('bert-base-cased')

In [150]:
tokens=tokenizer.tokenize('hello how are you ?')
tokens

['hello', 'how', 'are', 'you', '?']

In [152]:
token=tokenizer('hello my world',truncation=True,padding='max_length',return_tensors='pt')
token

{'input_ids': tensor([[  101, 19082,  1139,  1362,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])}

In [182]:
def tokenize_data(rows):
  return tokenizer(rows,truncation=True,padding='max_length',return_tensors='pt')

In [183]:
row1=df['text'].sample().item()
tokenized_row1=tokenize_data(row1)
tokenized_row1

{'input_ids': tensor([[  101,   146,  2059,  1115,  1142,  1110,  1141,  1104,  3019,  8079,
           112,   188,  1436,  3853,  1107,   170,  2523,   117,  1105,   146,
          1138,  1562,  1211,  1104,  1123,  5558,   119,   146,  1486,  1142,
          1111,  1103,  1148,  1159,  1113,  1778,  1165,   146,  1108,  1213,
          7840,   117,  1105,   146,  1108,  1177,  5528,   119,   146,  2824,
          1142,  2523,  1451,  1208,  1105,  1173,   117,  1105,   146,  1253,
          5548,  1122,  1304,  1277,   119,   146,  1221,  1115,  1292,  1552,
          1115,  1142,  2523,  1156,  1930,  1136, 13671,  1234,  1315,  1277,
           119,  1337,  1198,  2947,  1106,  1437,  1115,  1103,  1470,  2523,
          1105,  1778,  3703,  1144,  1562,  1315,  1277,  9429,  4289,  1107,
          1103,  1314,  3961,  1201,  1137,  1177,   119,   146,  1567,  5558,
          1115,  1202,  1136,  1437,  1103,  9429,  4068,   117,  1128,  1519,
          1240, 10405,  1202,  1103,  1250,  1111,  1128,   119,  1109,  2641,
          1107,  1142,  2523,  1108,  1499, 23555,   119, 12419, 14862,   117,
          1150,  1307,  1103,  2104,  1107,  1103,  1642,  1108,  1304,  1363,
           117,  1256,  1463,  1123,  1226,  1108,  1897,  1353,   119,  1153,
          1145,  1307,  1107,   170, 21359, 14791, 21361,  1189,  1111,  1778,
         11826,  1213,  1103,  1269,  1159,  1270,  1192,   112,  1325,  5091,
          3969,  2508,  5630,  1114,  1681,  7103,  1399,   119,   146,  1400,
          1103,  4583,  5642,  1149,  1104, 22431,  1124,  2158,  9349,   112,
           188,  2099,  1112,  1103, 26458,   119, 22431,  1108,  1177,  1363,
          1112,   170,  5141,  1114,   170,  1304,  2213, 25622,   119,  1667,
          7085, 16234,  1116,  1150,  1307,  1103,  2252,  1108,  2385,  3903,
           119,  1188,  1642,  5544,  1125,   170,  1974,  1104,  1177,  1270,
         12572,  1107,  1103,  4928,   117,  1133,   146,  1567,  1103,  2523,
          4050,   119,   146,  3023, 18029,  1142,  2523,  1106,  1234,  1150,
          1567,   170,  1363, 11826,  1443,  9429,  4289,   119,   146,  1522,
          1142,  2523,   170,  2992,  1104,  1978,   119,   102,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])}

In [191]:
from tokenizers import Tokenizer,models,trainers,pre_tokenizers
data=['hello my name is musheer','what are you doing','chalti kya khandala']

tokenizer=Tokenizer(models.BPE())
tokenizer.pre_tokenizers = pre_tokenizers.Whitespace()
trainer=trainers.BpeTrainer(vocab_size=100)
tk=tokenizer.train_from_iterator(data,trainer)
tokenizer.save('my-tokenizer.json')

In [192]:
from transformers import PreTrainedTokenizerFast

hf_tokenizer = PreTrainedTokenizerFast(
    tokenizer_file="/content/my-tokenizer.json",
    unk_token="[UNK]",
    pad_token="[PAD]",
    cls_token="[CLS]",
    sep_token="[SEP]",
    mask_token="[MASK]"
)
hf_tokenizer

PreTrainedTokenizerFast(name_or_path='', vocab_size=71, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	71: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	72: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	73: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	74: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	75: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [200]:
token=hf_tokenizer('hello my world',return_tensors='pt')
token

{'input_ids': tensor([[53, 40, 18,  0, 17, 12, 13,  9,  3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [228]:
import torch
from transformers import AutoModel , AutoTokenizer
tokenizer=AutoTokenizer.from_pretrained('bert-base-cased')
bert_model=AutoModel.from_pretrained('bert-base-uncased')
bert_model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [204]:
input=tokenizer('hello world ,',return_tensors='pt')
with torch.no_grad():
  output=bert_model(**input)
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1001,  0.0853,  0.1433,  ..., -0.1578,  0.0998,  0.1329],
         [-0.1009,  0.1553,  0.9068,  ..., -0.8728,  0.4241,  0.5517],
         [ 0.6204, -0.3617,  0.7727,  ..., -0.0154,  0.1215, -0.1189],
         [-0.8746, -0.9021, -0.0145,  ...,  0.0768,  0.3838,  0.2714],
         [ 0.7483,  0.1525, -0.3820,  ..., -0.0659, -0.6372, -0.1922]]]), pooler_output=tensor([[-7.4165e-01, -1.2076e-01,  5.2319e-01,  5.7028e-01, -4.0025e-01,
         -1.9995e-03,  8.2560e-01,  1.2002e-01,  2.7874e-01, -9.9924e-01,
          2.8970e-01, -1.2866e-01,  9.4379e-01, -1.6948e-01,  8.7261e-01,
         -3.9234e-01, -6.9706e-02, -3.9409e-01,  2.6160e-01, -7.5106e-01,
          3.7583e-01,  6.9480e-01,  6.0969e-01,  1.4532e-01,  2.6734e-01,
         -1.4707e-01, -3.8089e-01,  8.6380e-01,  8.9087e-01,  5.5914e-01,
         -6.6241e-01,  7.6364e-02, -9.3855e-01, -1.5938e-01,  4.3290e-01,
         -9.3860e-01,  3.5774e-02, -6.3561e-01, -8.6572e-03,  5.1369e-02,
         -7.9180e-01,  1.4714e-01,  9.7875e-01, -1.3898e-01, -3.0239e-01,
         -2.8810e-01, -9.9618e-01,  1.5415e-01, -7.5661e-01, -4.0063e-01,
         -3.2825e-01, -6.2971e-01,  7.1415e-02,  2.6872e-01,  2.6412e-01,
          4.3670e-01, -1.6933e-01,  7.3600e-02, -9.2638e-03, -3.7826e-01,
         -4.9186e-01,  1.3572e-01,  2.1690e-01, -8.0743e-01, -4.6930e-01,
         -5.0613e-01, -2.9182e-02, -1.5003e-01,  5.3535e-02, -8.2733e-02,
          7.2820e-01,  1.4351e-01,  3.0465e-01, -6.7080e-01, -4.4667e-01,
          4.9080e-02, -3.5789e-01,  9.9984e-01, -3.6840e-01, -9.1821e-01,
         -4.6912e-01, -3.2254e-01,  2.7878e-01,  5.5077e-01, -4.1250e-01,
         -9.9926e-01,  2.3988e-01, -2.0843e-02, -9.6172e-01,  1.1442e-01,
          1.7378e-01, -5.5370e-02, -5.3094e-01,  2.5480e-01, -1.9044e-01,
         -1.5420e-02, -1.9816e-01,  4.5411e-01, -7.5636e-02,  1.7316e-01,
         -1.4215e-03, -1.2211e-01,  1.0439e-01, -1.8296e-01,  5.3877e-02,
         -2.1388e-01, -3.0303e-01,  1.3357e-01, -2.4777e-01,  5.0962e-01,
          2.1999e-01, -1.2053e-01,  1.8210e-01, -8.8807e-01,  4.5964e-01,
         -1.3233e-01, -9.3140e-01, -2.7905e-01, -9.4770e-01,  4.7384e-01,
          1.4195e-01, -2.3080e-02,  8.9697e-01,  4.9972e-01,  1.1992e-01,
          3.5152e-02,  6.0596e-01, -9.9993e-01, -2.1040e-01, -7.2451e-02,
          1.9514e-01,  1.0863e-02, -9.1704e-01, -8.4681e-01,  3.9947e-01,
          8.9614e-01,  2.4368e-02,  9.6652e-01, -1.3752e-01,  8.0762e-01,
          1.5760e-01,  2.9286e-02, -4.1774e-01, -3.3050e-01,  2.0505e-01,
          2.9245e-01, -5.9757e-01,  8.4993e-02,  2.2166e-01, -2.1010e-01,
          1.9575e-01, -1.7117e-01,  4.3104e-01, -8.4383e-01, -3.2209e-01,
          8.7848e-01,  3.8502e-01,  5.0164e-01,  6.0270e-01, -1.1824e-01,
         -2.0881e-01,  7.1192e-01,  1.4068e-01,  2.0034e-01, -3.1832e-02,
          2.6991e-01, -3.4488e-02,  3.2373e-01, -7.4297e-01,  2.8352e-01,
          2.4884e-01, -1.1320e-01,  4.7775e-01, -9.2314e-01, -1.3904e-01,
          3.2505e-01,  9.5356e-01,  6.0122e-01,  1.1595e-01, -1.9485e-01,
         -1.1440e-01,  4.3814e-03, -8.5220e-01,  9.1018e-01, -9.2560e-02,
          1.3281e-01,  5.8127e-01, -2.5525e-02, -7.6306e-01, -3.6593e-01,
          7.6568e-01,  1.6989e-01, -6.8627e-01,  8.8585e-02, -3.4260e-01,
         -2.4855e-01,  4.0645e-01,  2.9594e-01, -1.2939e-01, -3.0457e-01,
          3.4023e-02,  8.1619e-01,  9.4434e-01,  6.1472e-01, -5.4988e-01,
          4.5048e-01, -7.9126e-01, -2.4923e-01,  8.3757e-02,  2.0289e-01,
          7.5882e-02,  9.7185e-01,  9.7218e-02, -5.0255e-02, -8.2509e-01,
         -9.4755e-01, -1.6464e-02, -7.7131e-01,  9.4711e-02, -5.1485e-01,
          3.6504e-02,  7.7870e-01, -1.3620e-01,  2.5915e-01, -9.6806e-01,
         -6.8094e-01,  2.6224e-01, -7.8842e-02,  2.0580e-01, -1.4126e-01,
         -3.4777e-01, -2.3887e-01, -3.7867e-01,  7.6195e-01,  7.5698e-01,
          6.1450e-01, -4.8587e-01,  7.8771e-01, -1.3568e-01,  7.9405e-01,
         -4.4099e-01,  9.2466e-01, -2.5601e-01,  3.3087e-01, -8.2909e-01,
          4.0209e-01, -8.0815e-01,  1.8359e-01,  1.2962e-02, -5.2473e-01,
         -2.9124e-01,  3.0273e-01,  1.2647e-01,  6.9092e-01, -3.6437e-01,
          9.8533e-01,  4.9986e-01, -8.5915e-01,  6.2440e-01, -1.8225e-02,
         -9.4284e-01, -3.2169e-01,  1.4832e-01, -6.7056e-01, -2.0642e-01,
         -2.3385e-01, -8.4918e-01,  8.3084e-01,  6.4810e-02,  9.6824e-01,
          2.4577e-01, -8.7461e-01, -1.7966e-01, -7.3560e-01, -2.0245e-01,
          3.3529e-02,  6.2161e-01, -1.4320e-01, -8.8093e-01,  2.6107e-01,
          3.1908e-01,  2.1291e-01,  5.7484e-01,  9.8021e-01,  9.7434e-01,
          9.0555e-01,  7.8621e-01,  7.8498e-01, -3.0940e-01,  4.6057e-01,
          9.9959e-01, -1.5874e-02, -9.9814e-01, -8.5926e-01, -4.7858e-01,
          2.8740e-01, -9.9991e-01, -3.6499e-05,  7.3079e-02, -7.7470e-01,
         -3.5897e-01,  9.2953e-01,  9.6680e-01, -9.9970e-01,  7.2152e-01,
          8.5361e-01, -3.9572e-01, -2.2630e-01, -3.1590e-02,  9.2297e-01,
          2.7047e-01,  1.8068e-01, -8.1053e-02,  1.7525e-01,  2.6631e-01,
         -7.7852e-01,  4.3304e-01,  5.3908e-01, -1.3322e-02,  2.3245e-02,
         -5.2536e-01, -8.5004e-01, -5.4107e-01, -1.1375e-01, -2.6414e-01,
         -8.6209e-01, -4.5252e-02, -4.6169e-01,  4.8655e-01, -3.5272e-02,
          6.6424e-02, -6.4229e-01,  1.2824e-01, -5.3927e-01,  3.7757e-01,
          3.8902e-01, -8.5039e-01, -5.1324e-01, -3.8353e-01, -3.5353e-01,
          3.3634e-01, -8.5210e-01,  9.2546e-01, -1.8603e-01, -3.3129e-01,
          9.9977e-01, -4.7151e-01, -7.5132e-01,  2.1119e-01,  5.9401e-02,
          1.8478e-03,  9.9956e-01,  5.3059e-02, -9.1775e-01, -3.1292e-01,
          8.5125e-02, -1.7026e-01, -1.6723e-01,  9.8996e-01, -3.9764e-02,
          4.4257e-01,  5.5870e-01,  8.9132e-01, -9.4774e-01, -2.7474e-01,
         -8.2587e-01, -8.8198e-01,  8.8788e-01,  8.3229e-01,  5.8190e-02,
         -4.7009e-01,  1.9860e-02,  1.5549e-02,  8.2571e-02, -9.1941e-01,
          4.6962e-01,  3.3831e-01, -2.0740e-02,  8.2574e-01, -8.3656e-01,
         -2.8030e-01,  3.2939e-01,  1.4834e-01,  3.4095e-01, -4.1765e-01,
          3.1669e-01, -1.9310e-01,  5.3217e-02, -1.2704e-01,  4.8427e-01,
         -9.1240e-01, -2.4020e-01,  9.9947e-01,  1.4177e-01, -6.9736e-01,
         -1.1495e-01,  2.0895e-02, -3.3742e-01,  1.2720e-01,  2.0163e-01,
         -1.4300e-01, -7.2165e-01, -3.5284e-01, -8.8088e-01, -9.3390e-01,
          6.5250e-01,  1.1484e-01, -1.4310e-01,  9.8471e-01,  1.5340e-01,
          5.8533e-03, -2.2081e-01, -2.9797e-01,  2.3627e-02,  4.9976e-01,
         -5.9809e-01,  8.8748e-01, -1.1239e-01,  2.9714e-01,  7.1603e-01,
          4.7694e-01, -2.0735e-01, -4.9041e-01, -1.0904e-02, -7.7095e-01,
          2.4510e-02, -8.3689e-01,  8.6122e-01, -5.2326e-01,  1.7339e-01,
          4.3776e-02, -3.2386e-01,  9.9967e-01,  6.6062e-01,  5.2132e-01,
         -6.0452e-01,  8.5714e-01, -3.0281e-01, -5.6286e-01, -1.4800e-01,
          4.0623e-02,  5.3951e-01, -1.0003e-01,  1.4813e-01, -9.0588e-01,
         -4.0718e-01, -2.6085e-01, -9.4957e-01, -9.5982e-01,  5.3542e-01,
          6.1954e-01, -6.1894e-02,  3.2407e-01, -4.3374e-01, -4.2993e-01,
         -3.9086e-02, -5.8366e-02, -8.3553e-01,  6.1964e-01, -1.4363e-01,
          3.3415e-01, -1.0501e-01,  2.7233e-01, -5.3024e-01,  6.5733e-01,
          6.7893e-01,  1.5078e-01,  1.3518e-03, -6.7401e-01,  6.8408e-01,
         -7.0506e-01,  4.5400e-01, -3.1176e-02,  9.9988e-01, -1.8825e-01,
         -2.5973e-01,  6.0727e-01,  5.1516e-01,  2.0528e-02,  5.8857e-02,
         -3.7424e-01,  5.9196e-02,  3.5794e-01,  5.2439e-01, -7.8817e-01,
         -1.4305e-01,  3.3710e-01, -7.1609e-01, -3.9578e-01,  5.8016e-01,
         -3.4341e-01, -2.0312e-02,  4.5218e-02,  1.2847e-01,  9.9252e-01,
         -1.5064e-01, -7.1469e-03, -2.9579e-01,  5.7091e-02, -1.4788e-01,
         -6.8488e-01,  9.9832e-01,  2.9877e-01, -2.4316e-01, -9.5631e-01,
          4.2963e-01, -8.5814e-01,  9.4591e-01,  5.7288e-01, -7.3684e-01,
          2.7360e-01,  2.4547e-01, -7.5424e-02,  6.4199e-01, -6.9851e-02,
         -2.0071e-01,  2.3678e-02,  1.1343e-01,  8.7391e-01, -2.7603e-01,
         -8.6610e-01, -4.3358e-01,  1.6769e-01, -8.7510e-01,  3.9185e-01,
         -3.3435e-01, -2.8003e-02, -1.1445e-01,  5.1338e-01,  8.6303e-01,
         -7.5943e-02, -9.2190e-01, -6.3577e-02, -1.0336e-01,  8.9560e-01,
          2.0423e-02, -2.7626e-01, -8.3489e-01, -4.6161e-01, -2.6653e-01,
          6.1023e-01, -8.4999e-01,  9.0006e-01, -9.4979e-01,  1.5806e-01,
          9.9864e-01,  1.3823e-01, -6.2672e-01,  4.6479e-02, -1.9519e-01,
          7.4429e-02,  4.5771e-01,  4.5867e-01, -8.7023e-01, -1.1490e-01,
         -6.3102e-02,  1.1128e-01, -1.2099e-01,  5.7753e-01,  4.7811e-01,
          8.5028e-02, -2.4618e-01, -3.8439e-01,  5.8504e-03,  2.6626e-01,
          5.7522e-01, -2.0409e-01, -3.5628e-02,  4.9378e-02, -1.1099e-01,
         -8.3011e-01, -3.1219e-02, -3.9559e-02, -7.5427e-01,  4.6416e-01,
         -9.9981e-01, -3.8493e-01, -4.9273e-01, -1.2438e-01,  6.8656e-01,
         -3.8850e-01, -2.4016e-01, -4.8134e-01,  4.5400e-01,  7.4115e-01,
          6.0301e-01, -1.5122e-02,  2.4133e-01, -5.6601e-01,  1.4637e-02,
         -2.8775e-02,  2.4421e-02,  2.0271e-01,  6.0920e-01, -2.9116e-02,
          9.9991e-01,  2.4742e-02, -2.9719e-01, -9.4169e-01,  1.4112e-01,
         -1.2986e-01,  9.8201e-01, -8.4278e-01, -8.4622e-01,  1.1908e-01,
         -2.5104e-01, -6.7335e-01,  7.2032e-02, -9.4507e-02, -4.3159e-01,
          3.4740e-01,  9.3216e-01,  8.1787e-01, -2.9408e-01,  1.6881e-01,
         -1.5074e-01, -2.6249e-01,  8.2813e-04, -5.9095e-01,  9.4613e-01,
          2.1643e-01,  7.8541e-01,  7.6083e-01,  3.3720e-01,  8.8321e-01,
          8.6069e-02,  6.3201e-01, -1.5832e-02,  9.9840e-01,  1.5102e-01,
         -8.4409e-01,  4.7372e-01, -9.5649e-01, -1.2396e-01, -9.0971e-01,
          9.2107e-02, -5.3075e-02,  6.7814e-01, -1.2257e-01,  8.9177e-01,
          6.2180e-01,  1.5969e-02,  2.4584e-01,  6.3408e-01,  2.1799e-01,
         -7.9370e-01, -9.3950e-01, -9.5106e-01,  3.9072e-03, -3.3391e-01,
          6.1279e-03,  1.4842e-01,  1.2110e-01,  1.8604e-01,  1.6058e-01,
         -9.9735e-01,  8.2089e-01,  2.9211e-01, -3.9146e-01,  8.6953e-01,
          1.4292e-02, -8.4878e-02,  1.1945e-01, -9.5558e-01, -9.2031e-01,
         -2.2918e-01, -1.3556e-01,  6.9592e-01,  3.7093e-01,  7.2978e-01,
          2.1199e-01, -4.0109e-01,  2.0750e-01,  4.5478e-01,  5.1405e-01,
         -9.6426e-01,  2.2257e-01,  3.4586e-01, -9.2847e-01,  8.8226e-01,
         -3.9200e-01, -1.5092e-01,  5.8773e-01,  3.0997e-01,  8.9590e-01,
          6.7178e-01,  4.0714e-01,  8.7751e-02,  4.1131e-01,  7.4638e-01,
          9.1669e-01,  9.6319e-01,  3.4686e-01,  6.5400e-01,  4.3522e-01,
          2.0612e-01, -1.9247e-01, -8.4113e-01,  1.4001e-02, -2.7997e-01,
          8.2032e-03,  9.5318e-02, -1.0802e-01, -9.3461e-01,  1.2743e-01,
         -2.7433e-02,  3.2351e-01, -2.2283e-01,  2.0003e-01, -2.7744e-01,
         -8.2720e-02, -5.4874e-01, -2.5605e-01,  4.0163e-01,  2.1076e-01,
          8.3117e-01, -1.2682e-01,  3.1191e-02, -4.2478e-01, -4.8195e-02,
          3.5215e-01, -8.0043e-01,  8.6078e-01,  7.3480e-02,  2.9707e-01,
         -3.2678e-01, -1.2995e-01,  1.5397e-01, -3.3133e-01, -2.3399e-01,
         -1.2137e-01, -5.7894e-01,  7.2561e-01,  3.1747e-01, -2.8772e-01,
         -3.1111e-01,  3.6510e-01,  2.2752e-01,  6.0720e-01,  3.7458e-01,
          3.6220e-01,  1.9606e-01, -9.9478e-02,  1.0015e-01, -5.6832e-02,
         -9.9747e-01,  2.9091e-01,  2.8343e-01, -3.6300e-01,  2.8757e-01,
         -5.0770e-01,  6.7298e-02, -9.4421e-01,  3.0642e-02, -4.9277e-01,
         -5.0250e-01, -3.9744e-01, -2.9104e-01,  3.0535e-01,  4.3029e-01,
         -3.9744e-01,  7.6607e-01,  2.0334e-01,  5.2027e-01,  3.5301e-01,
          3.5681e-01, -4.8345e-01,  8.0206e-01]]), hidden_states=None, past_key_values=None, attentions=None, cross_attentions=None)

In [229]:
from torch.nn.functional import cosine_similarity
sen1=['hello my name is musheer']
sen2=['hello my self musheer']

input1=tokenizer(sen1,return_tensors='pt')
input2=tokenizer(sen2,return_tensors='pt')

with torch.no_grad():
  output1=bert_model(**input1).last_hidden_state[0].mean(dim=0)
  output2=bert_model(**input2).last_hidden_state[0].mean(dim=0)

similarity=cosine_similarity(output1,output2,dim=0)
print('Similarity : ',round(similarity.item()*100,2),'%')

Similarity :  82.34 %

In [232]:
from sentence_transformers import SentenceTransformer
model=SentenceTransformer('all-MiniLM-L6-v2')
sen1='hello my name is musheer'
sen2='hello my self musheer'
emb1=model.encode(sen1,convert_to_tensor=True)
emb2=model.encode(sen2,convert_to_tensor=True)

similarity = cosine_similarity(emb1, emb2, dim=0)
print(f"Similarity: {similarity.item()*100:.2f} %")

Similarity: 74.30 %